
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.model.analyzer.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int PAR_DER = 10;
  public static final int H2_E = 30;
  public static final int FOR_E = 38;
  public static final int H2_B = 29;
  public static final int FOR_B = 37;
  public static final int POR = 15;
  public static final int H1_E = 28;
  public static final int TABLE_E = 23;
  public static final int INTEGER = 5;
  public static final int H1_B = 27;
  public static final int TABLE_B = 22;
  public static final int INT = 4;
  public static final int COR_DER = 12;
  public static final int HTML_E = 25;
  public static final int SEPARADOR = 8;
  public static final int ITERADOR = 21;
  public static final int TR_E = 32;
  public static final int HTML_B = 24;
  public static final int HASTA = 26;
  public static final int TR_B = 31;
  public static final int IGUAL = 19;
  public static final int DIV = 16;
  public static final int TH_E = 34;
  public static final int TH_B = 33;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int UNARY = 20;
  public static final int COMA = 7;
  public static final int TAG_FOR = 41;
  public static final int MENOS = 14;
  public static final int BR = 39;
  public static final int PAR_IZQ = 9;
  public static final int LITERAL = 3;
  public static final int PUNTO = 18;
  public static final int COR_IZQ = 11;
  public static final int STRING = 6;
  public static final int TD_E = 36;
  public static final int TEXT = 40;
  public static final int TD_B = 35;
  public static final int RESULT = 17;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "LITERAL",
  "INT",
  "INTEGER",
  "STRING",
  "COMA",
  "SEPARADOR",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "RESULT",
  "PUNTO",
  "IGUAL",
  "UNARY",
  "ITERADOR",
  "TABLE_B",
  "TABLE_E",
  "HTML_B",
  "HTML_E",
  "HASTA",
  "H1_B",
  "H1_E",
  "H2_B",
  "H2_E",
  "TR_B",
  "TR_E",
  "TH_B",
  "TH_E",
  "TD_B",
  "TD_E",
  "FOR_B",
  "FOR_E",
  "BR",
  "TEXT",
  "TAG_FOR"
  };
}

