// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/resources/lexico.jflex

package edu.mooncoder.rml.controllers.analyzer.lexic;

import java_cup.runtime.Symbol;

import edu.mooncoder.rml.controllers.builders.ErrorsReportBuilder;
import edu.mooncoder.rml.exceptions.AnalysisException;
import edu.mooncoder.rml.exceptions.lexical.NotRecognizedCharactersException;
import edu.mooncoder.rml.controllers.analyzer.syntax.Tokens;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class HtmlLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int COMMENT_OUT = 4;
  public static final int LITERAL = 6;
  public static final int TAGS = 8;
  public static final int VARIABLE = 10;
  public static final int FOR = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\u10fe\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\1\0\1\5\3\0\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\7\16\1\21\1\22\1\23\1\24\1\25\2\0\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\2\30\1\37\1\40\1\41\1\42\2\30\1\43\1\44"+
    "\1\45\1\46\5\30\1\47\1\50\1\51\1\0\1\52"+
    "\1\0\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\2\30\1\37\1\40\1\41\1\42\2\30"+
    "\1\43\1\44\1\45\1\46\5\30\66\0\1\30\21\0"+
    "\1\30\154\0\2\53\115\0\1\54\u0180\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\1"+
    "\1\17\3\4\1\20\1\21\3\1\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\1\2\2\5\1\1\31"+
    "\2\4\1\1\1\32\1\0\3\4\2\0\1\33\1\34"+
    "\1\35\1\36\1\37\1\0\1\40\6\0\1\41\1\42"+
    "\2\4\2\0\2\4\1\0\1\4\2\0\1\43\13\0"+
    "\1\44\1\4\1\0\1\4\2\0\2\4\1\0\1\4"+
    "\12\0\1\45\1\0\1\46\1\47\1\0\1\50\1\51"+
    "\1\52\1\4\1\0\1\4\2\0\2\4\1\0\1\4"+
    "\3\0\1\53\1\54\2\0\1\55\1\56\1\57\1\60"+
    "\1\0\1\4\1\0\1\4\1\0\1\61\1\4\2\62"+
    "\1\4\2\0\1\63\3\0\1\64\1\4\1\0\1\4"+
    "\2\65\1\0\1\66\1\0\1\67\1\4\1\0\2\70"+
    "\1\71\1\4\1\0\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\u013b\0\u0168\0\u013b\0\u0195\0\u013b\0\u013b\0\u013b\0\u013b"+
    "\0\u013b\0\u013b\0\u013b\0\u013b\0\u01c2\0\u013b\0\u01ef\0\u013b"+
    "\0\u021c\0\u0249\0\u0276\0\u013b\0\u013b\0\u0195\0\u02a3\0\u02d0"+
    "\0\u013b\0\u013b\0\u013b\0\u013b\0\u02fd\0\u013b\0\u032a\0\u0357"+
    "\0\u0384\0\u03b1\0\u03de\0\u040b\0\u0438\0\u0465\0\u0492\0\u013b"+
    "\0\u04bf\0\u04ec\0\u0519\0\u013b\0\u0546\0\u0573\0\u05a0\0\u05cd"+
    "\0\u05fa\0\u0627\0\u013b\0\u013b\0\u013b\0\u013b\0\u0357\0\u0654"+
    "\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0438\0\u0762\0\u013b"+
    "\0\u013b\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d"+
    "\0\u08ca\0\u08f7\0\u0924\0\u013b\0\u0951\0\u097e\0\u09ab\0\u09d8"+
    "\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13\0\u013b"+
    "\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b"+
    "\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89\0\u0db6\0\u0de3"+
    "\0\u0e10\0\u0e3d\0\u0e6a\0\u013b\0\u0e97\0\u013b\0\u013b\0\u0ec4"+
    "\0\u013b\0\u013b\0\u013b\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5"+
    "\0\u0fd2\0\u0fff\0\u102c\0\u1059\0\u1086\0\u10b3\0\u10e0\0\u013b"+
    "\0\u013b\0\u110d\0\u113a\0\u013b\0\u013b\0\u013b\0\u0e97\0\u1167"+
    "\0\u1194\0\u11c1\0\u11ee\0\u121b\0\u013b\0\u1248\0\u0195\0\u013b"+
    "\0\u1275\0\u12a2\0\u12cf\0\u013b\0\u12fc\0\u1329\0\u1356\0\u013b"+
    "\0\u1383\0\u13b0\0\u13dd\0\u013b\0\u140a\0\u1437\0\u013b\0\u1464"+
    "\0\u013b\0\u1491\0\u14be\0\u013b\0\u14eb\0\u013b\0\u1518\0\u1545"+
    "\0\u013b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\2\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\3\25\1\10\1\26"+
    "\1\27\1\30\1\10\10\14\1\31\4\14\1\32\1\33"+
    "\2\14\1\34\1\10\1\35\1\36\1\37\1\40\15\41"+
    "\1\42\37\41\15\43\1\41\7\43\1\44\27\43\2\45"+
    "\2\10\1\46\43\45\1\47\4\45\1\50\1\51\2\52"+
    "\1\50\1\53\15\50\1\54\31\50\1\10\2\11\1\12"+
    "\1\10\1\14\1\10\1\55\4\10\1\23\1\10\3\25"+
    "\2\10\1\56\2\10\15\14\1\32\3\14\1\34\1\10"+
    "\1\35\1\36\3\10\2\11\1\12\1\10\1\14\6\10"+
    "\1\23\1\10\3\25\1\10\1\26\1\57\1\10\1\60"+
    "\7\14\1\61\1\62\4\14\1\32\3\14\1\34\1\10"+
    "\1\35\1\36\1\63\1\10\57\0\1\11\57\0\1\14"+
    "\10\0\3\14\5\0\21\14\3\0\1\14\20\0\3\25"+
    "\51\0\1\64\17\0\1\65\24\0\1\14\10\0\3\14"+
    "\5\0\13\14\1\66\5\14\3\0\1\14\7\0\1\14"+
    "\10\0\3\14\5\0\4\14\1\67\14\14\3\0\1\14"+
    "\7\0\1\14\10\0\3\14\5\0\17\14\1\70\1\14"+
    "\3\0\1\14\43\0\1\71\60\0\1\72\7\0\2\45"+
    "\3\0\43\45\1\0\4\45\4\0\1\73\34\0\1\74"+
    "\1\0\1\75\1\0\1\76\7\0\2\77\2\0\1\77"+
    "\1\0\7\77\1\0\5\77\1\0\32\77\1\51\2\52"+
    "\1\77\1\0\7\77\1\0\5\77\1\0\31\77\1\0"+
    "\3\52\56\0\1\100\64\0\1\101\11\0\1\102\3\0"+
    "\1\103\1\0\1\104\7\0\1\105\10\0\3\106\1\0"+
    "\1\107\64\0\1\110\54\0\1\111\44\0\1\14\10\0"+
    "\3\14\5\0\1\112\20\14\3\0\1\14\7\0\1\14"+
    "\10\0\3\14\5\0\17\14\1\113\1\14\3\0\1\14"+
    "\47\0\1\114\54\0\1\115\14\0\1\14\10\0\3\14"+
    "\5\0\17\14\1\116\1\14\3\0\1\14\7\0\1\14"+
    "\10\0\3\14\5\0\16\14\1\117\2\14\3\0\1\14"+
    "\1\0\1\120\5\0\1\14\10\0\3\14\5\0\15\14"+
    "\1\121\3\14\3\0\1\14\47\0\1\122\52\0\1\123"+
    "\12\0\3\100\2\0\1\124\101\0\1\125\1\0\1\126"+
    "\7\0\1\127\52\0\1\130\53\0\1\131\31\0\1\132"+
    "\1\133\62\0\1\134\2\0\1\135\3\0\1\136\5\0"+
    "\1\137\16\0\1\140\54\0\1\14\10\0\3\14\5\0"+
    "\16\14\1\141\2\14\3\0\1\14\1\0\1\142\5\0"+
    "\1\14\10\0\3\14\5\0\4\14\1\143\14\14\3\0"+
    "\1\14\34\0\1\144\62\0\1\145\21\0\1\14\10\0"+
    "\3\14\5\0\4\14\1\146\14\14\3\0\1\14\7\0"+
    "\1\14\10\0\3\14\5\0\20\14\1\147\3\0\1\14"+
    "\50\0\1\150\13\0\1\14\10\0\3\14\5\0\10\14"+
    "\1\151\10\14\3\0\1\14\1\152\33\0\1\153\60\0"+
    "\1\152\14\0\1\152\43\0\1\154\31\0\1\155\1\156"+
    "\24\0\1\157\35\0\1\160\2\0\1\161\3\0\1\162"+
    "\5\0\1\163\36\0\1\164\72\0\1\165\36\0\1\166"+
    "\54\0\1\167\56\0\1\170\52\0\1\171\54\0\1\172"+
    "\54\0\1\173\34\0\1\14\10\0\3\14\5\0\17\14"+
    "\1\174\1\14\3\0\1\14\47\0\1\175\14\0\1\14"+
    "\10\0\3\14\5\0\15\14\1\176\3\14\3\0\1\14"+
    "\45\0\1\177\50\0\1\200\22\0\1\14\10\0\3\14"+
    "\5\0\6\14\1\201\12\14\3\0\1\14\7\0\1\14"+
    "\10\0\3\14\5\0\11\14\1\202\7\14\3\0\1\14"+
    "\41\0\1\203\22\0\1\14\10\0\3\14\5\0\13\14"+
    "\1\204\5\14\3\0\1\14\43\0\1\205\47\0\1\206"+
    "\63\0\1\207\36\0\1\210\54\0\1\211\67\0\1\212"+
    "\43\0\1\213\52\0\1\214\54\0\1\215\54\0\1\216"+
    "\30\0\3\217\110\0\1\220\22\0\1\14\10\0\3\14"+
    "\5\0\1\221\20\14\3\0\1\14\30\0\1\222\33\0"+
    "\1\14\10\0\3\14\5\0\1\223\20\14\3\0\1\14"+
    "\30\0\1\224\53\0\1\225\34\0\1\14\10\0\3\14"+
    "\5\0\4\14\1\226\14\14\3\0\1\14\7\0\1\14"+
    "\10\0\3\14\5\0\17\14\1\227\1\14\3\0\1\14"+
    "\47\0\1\230\14\0\1\14\10\0\3\14\5\0\6\14"+
    "\1\231\12\14\3\0\1\14\36\0\1\232\52\0\1\233"+
    "\47\0\1\234\66\0\1\235\54\0\1\236\47\0\1\237"+
    "\23\0\3\222\1\0\1\14\10\0\3\14\1\240\4\0"+
    "\21\14\3\0\1\14\3\0\3\222\15\0\1\240\40\0"+
    "\1\14\10\0\3\14\5\0\3\14\1\241\15\14\3\0"+
    "\1\14\33\0\1\242\30\0\1\14\10\0\3\14\5\0"+
    "\15\14\1\243\3\14\3\0\1\14\3\0\2\244\1\245"+
    "\1\0\1\14\10\0\3\14\5\0\21\14\3\0\1\14"+
    "\3\0\2\244\1\245\114\0\1\246\36\0\1\247\61\0"+
    "\1\250\47\0\1\251\34\0\1\14\10\0\3\14\5\0"+
    "\14\14\1\252\4\14\3\0\1\14\44\0\1\253\13\0"+
    "\2\254\1\255\1\0\1\14\10\0\3\14\5\0\21\14"+
    "\3\0\1\14\4\0\1\244\53\0\2\254\1\255\76\0"+
    "\1\256\34\0\1\14\10\0\3\14\5\0\15\14\1\257"+
    "\3\14\3\0\1\14\45\0\1\260\13\0\1\254\53\0"+
    "\3\260\1\0\1\14\10\0\3\14\1\261\4\0\21\14"+
    "\3\0\1\14\3\0\3\260\15\0\1\261\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5490];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\2\11\1\1\1\11\1\1\10\11\1\1\1\11"+
    "\1\1\1\11\3\1\2\11\3\1\4\11\1\1\1\11"+
    "\11\1\1\11\3\1\1\11\1\0\3\1\2\0\4\11"+
    "\1\1\1\0\1\1\6\0\2\11\2\1\2\0\2\1"+
    "\1\0\1\1\2\0\1\11\13\0\1\11\1\1\1\0"+
    "\1\1\2\0\2\1\1\0\1\1\12\0\1\11\1\0"+
    "\2\11\1\0\3\11\1\1\1\0\1\1\2\0\2\1"+
    "\1\0\1\1\3\0\2\11\2\0\3\11\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\11\2\1\1\11\1\1"+
    "\2\0\1\11\3\0\1\11\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\11\1\0\1\11\1\1\1\0\1\11"+
    "\1\1\1\11\1\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private int stateToReturn = YYINITIAL;
  private final StringBuffer string = new StringBuffer();
  private final StringBuffer error = new StringBuffer();

  private Symbol symbol(int type) {
    addError();
    return new Symbol(type, yyline + 1, yycolumn + 1);
  }

  private void addError() {
    if (error.length() != 0) {
      AnalysisException exception = new NotRecognizedCharactersException(error.toString(), yyline + 1, yycolumn - error.length());
      ErrorsReportBuilder.add(exception);
      error.setLength(0);
    }
  }

  private Symbol symbol(int type, Object value) {
    addError();
    if (type == Tokens.LITERAL)
      return new Symbol(type, yyline + 1, yycolumn - string.length(), value);
    else
      return new Symbol(type, yyline + 1, yycolumn + 1, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public HtmlLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Tokens.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error.append(yytext());
            }
            // fall through
          case 59: break;
          case 2:
            { addError();
            }
            // fall through
          case 60: break;
          case 3:
            { addError(); string.setLength(0); yybegin(LITERAL);
            }
            // fall through
          case 61: break;
          case 4:
            { return symbol(Tokens.ID, yytext());
            }
            // fall through
          case 62: break;
          case 5:
            { return symbol(Tokens.PAR_IZQ);
            }
            // fall through
          case 63: break;
          case 6:
            { return symbol(Tokens.PAR_DER);
            }
            // fall through
          case 64: break;
          case 7:
            { return symbol(Tokens.POR);
            }
            // fall through
          case 65: break;
          case 8:
            { return symbol(Tokens.MAS);
            }
            // fall through
          case 66: break;
          case 9:
            { return symbol(Tokens.COMA);
            }
            // fall through
          case 67: break;
          case 10:
            { return symbol(Tokens.MENOS);
            }
            // fall through
          case 68: break;
          case 11:
            { return symbol(Tokens.PUNTO);
            }
            // fall through
          case 69: break;
          case 12:
            { return symbol(Tokens.DIV);
            }
            // fall through
          case 70: break;
          case 13:
            { return symbol(Tokens.INT, Integer.parseInt(yytext()));
            }
            // fall through
          case 71: break;
          case 14:
            { return symbol(Tokens.SEPARADOR);
            }
            // fall through
          case 72: break;
          case 15:
            { return symbol(Tokens.IGUAL);
            }
            // fall through
          case 73: break;
          case 16:
            { return symbol(Tokens.COR_IZQ);
            }
            // fall through
          case 74: break;
          case 17:
            { return symbol(Tokens.COR_DER);
            }
            // fall through
          case 75: break;
          case 18:
            { /* skip */
            }
            // fall through
          case 76: break;
          case 19:
            { yybegin(COMMENT_OUT);
            }
            // fall through
          case 77: break;
          case 20:
            { yybegin(COMMENT);
            }
            // fall through
          case 78: break;
          case 21:
            { yybegin(stateToReturn);
            }
            // fall through
          case 79: break;
          case 22:
            { string.append(yytext());
            }
            // fall through
          case 80: break;
          case 23:
            { yybegin(YYINITIAL); return symbol(Tokens.LITERAL, string.toString());
            }
            // fall through
          case 81: break;
          case 24:
            { string.append('\\');
            }
            // fall through
          case 82: break;
          case 25:
            { yybegin(TAGS); return symbol(Tokens.TAG_FOR);
            }
            // fall through
          case 83: break;
          case 26:
            { addError(); stateToReturn = YYINITIAL; yybegin(COMMENT);
            }
            // fall through
          case 84: break;
          case 27:
            { string.append('\"');
            }
            // fall through
          case 85: break;
          case 28:
            { string.append('\n');
            }
            // fall through
          case 86: break;
          case 29:
            { string.append('\r');
            }
            // fall through
          case 87: break;
          case 30:
            { string.append('\t');
            }
            // fall through
          case 88: break;
          case 31:
            { return symbol(Tokens.TEXT, yytext());
            }
            // fall through
          case 89: break;
          case 32:
            { addError(); stateToReturn = TAGS; yybegin(COMMENT);
            }
            // fall through
          case 90: break;
          case 33:
            { addError(); stateToReturn = VARIABLE; yybegin(COMMENT);
            }
            // fall through
          case 91: break;
          case 34:
            { addError(); stateToReturn = FOR; yybegin(COMMENT);
            }
            // fall through
          case 92: break;
          case 35:
            { addError(); yybegin(VARIABLE);
            }
            // fall through
          case 93: break;
          case 36:
            { addError(); yybegin(TAGS);
            }
            // fall through
          case 94: break;
          case 37:
            { return symbol(Tokens.BR);
            }
            // fall through
          case 95: break;
          case 38:
            { return symbol(Tokens.H1_B);
            }
            // fall through
          case 96: break;
          case 39:
            { return symbol(Tokens.H2_B);
            }
            // fall through
          case 97: break;
          case 40:
            { return symbol(Tokens.TD_B);
            }
            // fall through
          case 98: break;
          case 41:
            { return symbol(Tokens.TH_B);
            }
            // fall through
          case 99: break;
          case 42:
            { return symbol(Tokens.TR_B);
            }
            // fall through
          case 100: break;
          case 43:
            { return symbol(Tokens.H1_E);
            }
            // fall through
          case 101: break;
          case 44:
            { return symbol(Tokens.H2_E);
            }
            // fall through
          case 102: break;
          case 45:
            { return symbol(Tokens.TD_E);
            }
            // fall through
          case 103: break;
          case 46:
            { return symbol(Tokens.TH_E);
            }
            // fall through
          case 104: break;
          case 47:
            { return symbol(Tokens.TR_E);
            }
            // fall through
          case 105: break;
          case 48:
            { yybegin(FOR); return symbol(Tokens.FOR_B);
            }
            // fall through
          case 106: break;
          case 49:
            { string.setLength(0); yybegin(TAGS); return symbol(Tokens.HTML_B);
            }
            // fall through
          case 107: break;
          case 50:
            { return symbol(Tokens.RESULT);
            }
            // fall through
          case 108: break;
          case 51:
            { return symbol(Tokens.FOR_E);
            }
            // fall through
          case 109: break;
          case 52:
            { return symbol(Tokens.HASTA);
            }
            // fall through
          case 110: break;
          case 53:
            { return symbol(Tokens.STRING);
            }
            // fall through
          case 111: break;
          case 54:
            { return symbol(Tokens.HTML_E);
            }
            // fall through
          case 112: break;
          case 55:
            { return symbol(Tokens.TABLE_B);
            }
            // fall through
          case 113: break;
          case 56:
            { return symbol(Tokens.INTEGER);
            }
            // fall through
          case 114: break;
          case 57:
            { return symbol(Tokens.TABLE_E);
            }
            // fall through
          case 115: break;
          case 58:
            { return symbol(Tokens.ITERADOR);
            }
            // fall through
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
