
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.osrn.controllers.analyzer.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int INT = 4;
  public static final int COLON = 9;
  public static final int LITERAL = 3;
  public static final int CUR_IZQ = 5;
  public static final int EOF = 0;
  public static final int BRA_IZQ = 7;
  public static final int CUR_DER = 6;
  public static final int ID = 2;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int BRA_DER = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "LITERAL",
  "INT",
  "CUR_IZQ",
  "CUR_DER",
  "BRA_IZQ",
  "BRA_DER",
  "COLON",
  "COMMA"
  };
}

