
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.controllers.analyzer.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int RELATIONAL2 = 41;
  public static final int PAR_DER = 20;
  public static final int RELATIONAL1 = 40;
  public static final int POR = 33;
  public static final int CHAR = 11;
  public static final int VISIBILITY = 5;
  public static final int ENTERO = 9;
  public static final int CASE = 44;
  public static final int SEPARADOR = 13;
  public static final int FOR = 25;
  public static final int IGUAL = 35;
  public static final int TYPE = 17;
  public static final int BOOL = 42;
  public static final int LLA_DER = 16;
  public static final int CLASS = 4;
  public static final int DIV = 32;
  public static final int IF = 23;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 10;
  public static final int RETURN = 34;
  public static final int UNARY = 37;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int MENOS = 29;
  public static final int MOD = 31;
  public static final int PAR_IZQ = 19;
  public static final int BREAK = 22;
  public static final int VOID = 8;
  public static final int SWITCH = 36;
  public static final int IMPORT = 3;
  public static final int NEGAR = 39;
  public static final int COLON = 14;
  public static final int LITERAL = 27;
  public static final int ELSE = 24;
  public static final int PUNTO = 12;
  public static final int PACKAGE = 2;
  public static final int WHILE = 43;
  public static final int FINAL = 6;
  public static final int DEFAULT = 45;
  public static final int IGUAL_ = 38;
  public static final int LOGIC = 21;
  public static final int LLA_IZQ = 15;
  public static final int DO = 30;
  public static final int MAS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "VISIBILITY",
  "FINAL",
  "ID",
  "VOID",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "PUNTO",
  "SEPARADOR",
  "COLON",
  "LLA_IZQ",
  "LLA_DER",
  "TYPE",
  "COMA",
  "PAR_IZQ",
  "PAR_DER",
  "LOGIC",
  "BREAK",
  "IF",
  "ELSE",
  "FOR",
  "NEW",
  "LITERAL",
  "MAS",
  "MENOS",
  "DO",
  "MOD",
  "DIV",
  "POR",
  "RETURN",
  "IGUAL",
  "SWITCH",
  "UNARY",
  "IGUAL_",
  "NEGAR",
  "RELATIONAL1",
  "RELATIONAL2",
  "BOOL",
  "WHILE",
  "CASE",
  "DEFAULT"
  };
}

