
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.copy.controllers.analyzer.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int ID = 2;
  public static final int SEMICOLON = 4;
  public static final int PATH = 3;
  public static final int error = 1;
  public static final int SEPARATOR = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "PATH",
  "SEMICOLON",
  "SEPARATOR"
  };
}

