
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.model.analyzer.syntax;

import edu.mooncoder.model.containers.Osrn;
import edu.mooncoder.model.wrapper.*;
import edu.mooncoder.model.analyzer.lexic.JsonLexer;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class JsonParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Tokens.class;
}

  /** Default constructor. */
  @Deprecated
  public JsonParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public JsonParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public JsonParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\032\000\002\002\004\000\002\002\003\000\002\007" +
    "\005\000\002\010\005\000\002\010\004\000\002\011\003" +
    "\000\002\011\005\000\002\011\005\000\002\011\005\000" +
    "\002\006\003\000\002\006\002\000\002\005\003\000\002" +
    "\005\005\000\002\005\005\000\002\004\005\000\002\004" +
    "\005\000\002\004\004\000\002\004\004\000\002\004\005" +
    "\000\002\004\005\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\046\000\004\011\006\001\002\000\004\002\050\001" +
    "\002\000\004\002\000\001\002\000\010\004\007\005\010" +
    "\012\ufff7\001\002\000\006\003\044\015\045\001\002\000" +
    "\006\003\020\015\021\001\002\000\004\012\017\001\002" +
    "\000\006\012\ufff8\016\014\001\002\000\006\012\ufff6\016" +
    "\ufff6\001\002\000\010\003\015\004\007\005\010\001\002" +
    "\000\006\012\ufff4\016\ufff4\001\002\000\006\012\ufff5\016" +
    "\ufff5\001\002\000\014\002\uffff\012\uffff\014\uffff\015\uffff" +
    "\016\uffff\001\002\000\006\012\ufff0\016\ufff0\001\002\000" +
    "\020\003\031\005\022\006\023\007\024\010\025\011\006" +
    "\013\026\001\002\000\012\012\uffed\014\uffed\015\uffed\016" +
    "\uffed\001\002\000\012\012\uffec\014\uffec\015\uffec\016\uffec" +
    "\001\002\000\012\012\uffeb\014\uffeb\015\uffeb\016\uffeb\001" +
    "\002\000\012\012\uffea\014\uffea\015\uffea\016\uffea\001\002" +
    "\000\020\005\022\006\023\007\024\010\025\011\006\013" +
    "\026\014\033\001\002\000\012\012\uffe8\014\uffe8\015\uffe8" +
    "\016\uffe8\001\002\000\012\012\uffe9\014\uffe9\015\uffe9\016" +
    "\uffe9\001\002\000\006\012\uffee\016\uffee\001\002\000\006" +
    "\012\ufff2\016\ufff2\001\002\000\012\012\ufffd\014\ufffd\015" +
    "\ufffd\016\ufffd\001\002\000\010\014\ufffc\015\ufffc\016\ufffc" +
    "\001\002\000\010\014\037\015\040\016\036\001\002\000" +
    "\020\003\042\005\022\006\023\007\024\010\025\011\006" +
    "\013\026\001\002\000\012\012\ufffe\014\ufffe\015\ufffe\016" +
    "\ufffe\001\002\000\004\003\041\001\002\000\010\014\ufffa" +
    "\015\ufffa\016\ufffa\001\002\000\010\014\ufff9\015\ufff9\016" +
    "\ufff9\001\002\000\010\014\ufffb\015\ufffb\016\ufffb\001\002" +
    "\000\006\012\ufff1\016\ufff1\001\002\000\020\003\046\005" +
    "\022\006\023\007\024\010\025\011\006\013\026\001\002" +
    "\000\006\012\uffef\016\uffef\001\002\000\006\012\ufff3\016" +
    "\ufff3\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\046\000\006\002\003\007\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\004\012\005\011\006\010" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\015" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\003\031\007\027\010\026" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\003\033\007\027\010\026" +
    "\011\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\042\007\027\010" +
    "\026\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\003\046\007\027\010\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$JsonParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$JsonParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$JsonParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  private Osrn osrn;

  public Osrn getOsrn() { return osrn; }

  public JsonParser(JsonLexer lexer) {
    super(lexer);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$JsonParser$actions {
  private final JsonParser parser;

  /** Constructor */
  CUP$JsonParser$actions(JsonParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$JsonParser$do_action_part00000000(
    int                        CUP$JsonParser$act_num,
    java_cup.runtime.lr_parser CUP$JsonParser$parser,
    java.util.Stack            CUP$JsonParser$stack,
    int                        CUP$JsonParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$JsonParser$result;

      /* select the action based on the action number */
      switch (CUP$JsonParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= syntax EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		RESULT = start_val;
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$JsonParser$parser.done_parsing();
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // syntax ::= content 
            {
              Object RESULT =null;
		 osrn = OsrnWrapper.close(); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("syntax",0, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // content ::= CUR_IZQ obj_ CUR_DER 
            {
              OsrnWrapper RESULT =null;

              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("content",5, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // array ::= BRA_IZQ array_ BRA_DER 
            {
              OsrnWrapper RESULT =null;
		int arrayleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int arrayright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		OsrnWrapper array = (OsrnWrapper)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;

              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("array",6, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // array ::= BRA_IZQ BRA_DER 
            {
              OsrnWrapper RESULT =null;
		 ArrayWrapper.addEmpty(); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("array",6, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // array_ ::= value 
            {
              OsrnWrapper RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 ArrayWrapper.addFirst(value); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("array_",7, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // array_ ::= array_ COMMA value 
            {
              OsrnWrapper RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 ArrayWrapper.add(value); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("array_",7, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // array_ ::= array_ COLON error 
            {
              OsrnWrapper RESULT =null;
		int colonleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int colonright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		Object colon = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		 System.out.println("Se esperaba una coma o un ']'"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("array_",7, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // array_ ::= array_ COMMA error 
            {
              OsrnWrapper RESULT =null;
		int commaleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int commaright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		Object comma = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		 System.out.println("Se esperaba un <valor>"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("array_",7, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // obj_ ::= obj 
            {
              OsrnWrapper RESULT =null;

              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("obj_",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // obj_ ::= 
            {
              OsrnWrapper RESULT =null;
		 OsrnWrapper.addEmpty(); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("obj_",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // obj ::= pair 
            {
              OsrnWrapper RESULT =null;
		 OsrnWrapper.addFirstPair(PairWrapper.getPair()); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("obj",3, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // obj ::= obj COMMA pair 
            {
              OsrnWrapper RESULT =null;
		 OsrnWrapper.addPair(PairWrapper.getPair()); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("obj",3, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // obj ::= obj COMMA error 
            {
              OsrnWrapper RESULT =null;
		 System.out.println("Se esperaba un '}' o un par clave-valor"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("obj",3, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // pair ::= ID COLON value 
            {
              OsrnWrapper RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 PairWrapper.setPair(key, value); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("pair",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // pair ::= LITERAL COLON value 
            {
              OsrnWrapper RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 PairWrapper.setPair(key, value); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("pair",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // pair ::= ID error 
            {
              OsrnWrapper RESULT =null;
		 System.out.println("Se esperaba un ':'"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("pair",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // pair ::= LITERAL error 
            {
              OsrnWrapper RESULT =null;
		 System.out.println("Se esperaba un ':'"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("pair",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // pair ::= ID COLON error 
            {
              OsrnWrapper RESULT =null;
		 System.out.println("Se esperaba un <valor>"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("pair",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // pair ::= LITERAL COLON error 
            {
              OsrnWrapper RESULT =null;
		 System.out.println("Se esperaba un <valor>"); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("pair",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // value ::= LITERAL 
            {
              Object RESULT =null;
		int objleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int objright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		String obj = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 RESULT = obj; 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("value",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // value ::= NUMBER 
            {
              Object RESULT =null;
		int objleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int objright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		double obj = (double)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 RESULT = obj; 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("value",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // value ::= BOOLEAN 
            {
              Object RESULT =null;
		int objleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int objright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		boolean obj = (boolean)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 RESULT = obj; 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("value",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // value ::= NULL 
            {
              Object RESULT =null;
		int objleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int objright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		Object obj = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		 RESULT = obj; 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("value",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // value ::= content 
            {
              Object RESULT =null;
		 RESULT = OsrnWrapper.close(); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("value",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // value ::= array 
            {
              Object RESULT =null;
		 RESULT = ArrayWrapper.close(); 
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("value",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$JsonParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$JsonParser$do_action(
    int                        CUP$JsonParser$act_num,
    java_cup.runtime.lr_parser CUP$JsonParser$parser,
    java.util.Stack            CUP$JsonParser$stack,
    int                        CUP$JsonParser$top)
    throws java.lang.Exception
    {
              return CUP$JsonParser$do_action_part00000000(
                               CUP$JsonParser$act_num,
                               CUP$JsonParser$parser,
                               CUP$JsonParser$stack,
                               CUP$JsonParser$top);
    }
}

}
